Repository Fill-ENERGY/BackEnd_Server, pull requests merged in 2024-08, with the labels that each got.

#22 ✨ [FEAT] 게시글 CRUD API 구현 (#14)
  src/main/java/com/example/template/FillEnergyApplication.java
  src/main/java/com/example/template/domain/board/controller/BoardController.java
  src/main/java/com/example/template/domain/board/controller/CommentController.java
  src/main/java/com/example/template/domain/board/dto/request/BoardRequestDTO.java
  src/main/java/com/example/template/domain/board/dto/response/BoardResponseDTO.java
  src/main/java/com/example/template/domain/board/dto/response/CommentResponseDTO.java
  src/main/java/com/example/template/domain/board/entity/Board.java
  src/main/java/com/example/template/domain/board/entity/BoardImg.java
  src/main/java/com/example/template/domain/board/entity/BoardLike.java
  src/main/java/com/example/template/domain/board/entity/Comment.java
  src/main/java/com/example/template/domain/board/entity/CommentImg.java
  src/main/java/com/example/template/domain/board/entity/enums/Category.java
  src/main/java/com/example/template/domain/board/entity/enums/HelpStatus.java
  src/main/java/com/example/template/domain/board/exception/BoardErrorCode.java
  src/main/java/com/example/template/domain/board/exception/BoardException.java
  src/main/java/com/example/template/domain/board/repository/BoardLikeRepository.java
  src/main/java/com/example/template/domain/board/repository/BoardRepository.java
  src/main/java/com/example/template/domain/board/repository/CommentRepository.java
  src/main/java/com/example/template/domain/board/repository/MemberRepository.java
  src/main/java/com/example/template/domain/board/service/commandService/BoardCommandService.java
  src/main/java/com/example/template/domain/board/service/commandService/BoardCommandServiceImpl.java
  src/main/java/com/example/template/domain/board/service/queryService/BoardQueryService.java
  src/main/java/com/example/template/domain/board/service/queryService/BoardQueryServiceImpl.java
  src/test/java/com/example/template/FillEnergyApplicationTests.java
Labels: ✨ Feature, ♻️ Refactor, 💄 style

#13 ✨ feat: 쪽지 API 구현 (#11)
  build.gradle
  src/main/java/com/example/template/domain/member/repository/MemberRepository.java
  src/main/java/com/example/template/domain/message/controller/MessageController.java
  src/main/java/com/example/template/domain/message/dto/request/MessageRequestDTO.java
  src/main/java/com/example/template/domain/message/dto/response/MessageResponseDTO.java
  src/main/java/com/example/template/domain/message/entity/Message.java
  src/main/java/com/example/template/domain/message/entity/MessageParticipant.java
  src/main/java/com/example/template/domain/message/entity/MessageThread.java
  src/main/java/com/example/template/domain/message/exception/MessageErrorCode.java
  src/main/java/com/example/template/domain/message/exception/MessageException.java
  src/main/java/com/example/template/domain/message/repository/MessageParticipantRepository.java
  src/main/java/com/example/template/domain/message/repository/MessageRepository.java
  src/main/java/com/example/template/domain/message/repository/MessageThreadRepository.java
  src/main/java/com/example/template/domain/message/service/MessageCommandService.java
  src/main/java/com/example/template/domain/message/service/MessageCommandServiceImpl.java
  src/main/java/com/example/template/domain/message/service/MessageQueryService.java
  src/main/java/com/example/template/domain/message/service/MessageQueryServiceImpl.java
Labels: ✨ Feature

#18 ✨ feat: 충전소 API 구현 (#10)
  build.gradle
  src/main/java/com/example/template/FillEnergyApplication.java
  src/main/java/com/example/template/domain/station/controller/StationController.java
  src/main/java/com/example/template/domain/station/dto/response/StationOpenApiResponse.java
  src/main/java/com/example/template/domain/station/dto/response/StationResponseDTO.java
  src/main/java/com/example/template/domain/station/entity/Station.java
  src/main/java/com/example/template/domain/station/enums/SortType.java
  src/main/java/com/example/template/domain/station/exception/StationErrorCode.java
  src/main/java/com/example/template/domain/station/exception/StationException.java
  src/main/java/com/example/template/domain/station/exception/StationOpenAPIRuntimeException.java
  src/main/java/com/example/template/domain/station/repository/StationRepository.java
  src/main/java/com/example/template/domain/station/service/StationCommandService.java
  src/main/java/com/example/template/domain/station/service/StationQueryService.java
  src/main/java/com/example/template/domain/station/service/impl/StationCommandServiceImpl.java
  src/main/java/com/example/template/domain/station/service/impl/StationQueryServiceImpl.java
  src/main/java/com/example/template/domain/station/util/StationUtil.java
  src/main/java/com/example/template/global/config/WebClientConfig.java
Labels: ✨ Feature

#23 ✨ feat: 프로필 API 구현 (#12)
  src/main/java/com/example/template/domain/member/controller/MemberController.java
  src/main/java/com/example/template/domain/member/dto/ProfileRequestDTO.java
  src/main/java/com/example/template/domain/member/dto/ProfileResponseDTO.java
  src/main/java/com/example/template/domain/member/entity/Member.java
  src/main/java/com/example/template/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/template/domain/member/exception/MemberException.java
  src/main/java/com/example/template/domain/member/repository/MemberRepository.java
  src/main/java/com/example/template/domain/member/service/MemberCommandService.java
  src/main/java/com/example/template/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/template/domain/member/service/MemberQueryService.java
  src/main/java/com/example/template/domain/member/service/MemberQueryServiceImpl.java
Labels: ✨ Feature

#29 ♻️ refactor: Report 엔티티 구조변경(#28)
  src/main/java/com/example/template/domain/report/entity/Report.java
  src/main/java/com/example/template/domain/report/entity/ReportType.java
Labels: ♻️ Refactor

#31 ♻️ refactor: S3 의존성 변경 및 코드 리팩토링(#19)
  build.gradle
  src/main/java/com/example/template/global/config/aws/S3Config.java
  src/main/java/com/example/template/global/config/aws/S3Manager.java
  src/main/java/com/example/template/global/util/s3/entity/Uuid.java
  src/main/java/com/example/template/global/util/s3/exxception/S3ErrorCode.java
  src/main/java/com/example/template/global/util/s3/exxception/S3Exception.java
  src/main/java/com/example/template/global/util/s3/repository/UuidRepository.java
Labels: ♻️ Refactor

#35 🚑 [HOTFIX] 시큐리티 필터 관련 오류 수정 (#34)
  src/main/java/com/example/template/domain/member/jwt/filter/JwtAuthenticationFilter.java
Labels: 🐞 Fix

#33 ✨ [FEAT] 신고 API 구현 (#24)
  src/main/java/com/example/template/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/template/domain/report/controller/ReportController.java
  src/main/java/com/example/template/domain/report/dto/request/ReportRequestDTO.java
  src/main/java/com/example/template/domain/report/dto/response/ReportResponseDTO.java
  src/main/java/com/example/template/domain/report/exception/ReportErrorCode.java
  src/main/java/com/example/template/domain/report/exception/ReportException.java
  src/main/java/com/example/template/domain/report/repository/ReportRepository.java
  src/main/java/com/example/template/domain/report/service/ReportCommandService.java
  src/main/java/com/example/template/domain/report/service/ReportCommandServiceImpl.java
  src/main/java/com/example/template/domain/report/service/ReportQueryService.java
  src/main/java/com/example/template/domain/report/service/ReportQueryServiceImpl.java
Labels: ✨ Feature

#40 🐛 fix : ReportRequestDTO 수정(#39)
  src/main/java/com/example/template/domain/report/dto/request/ReportRequestDTO.java
  src/main/java/com/example/template/domain/report/dto/response/ReportResponseDTO.java
Labels: 🐞 Fix

#37 ♻️ refactor: report 엔티티 구조 변경 (#36)
  src/main/java/com/example/template/domain/report/entity/Report.java
  src/main/java/com/example/template/domain/report/entity/ReportCategory.java
  src/main/java/com/example/template/domain/report/entity/ReportContent.java
  src/main/java/com/example/template/domain/report/entity/ReportType.java
Labels: ♻️ Refactor

#42 ♻️ refactor : 신고 로직 변경
  src/main/java/com/example/template/domain/report/dto/request/ReportRequestDTO.java
  src/main/java/com/example/template/domain/report/dto/response/ReportResponseDTO.java
  src/main/java/com/example/template/domain/report/repository/ReportContentRepository.java
  src/main/java/com/example/template/domain/report/repository/ReportRepository.java
  src/main/java/com/example/template/domain/report/service/ReportCommandServiceImpl.java
Labels: ♻️ Refactor

#46 ♻️ refactor: 쪽지 로직 변경 (#32)
  src/main/java/com/example/template/domain/message/controller/MessageController.java
  src/main/java/com/example/template/domain/message/dto/request/MessageRequestDTO.java
  src/main/java/com/example/template/domain/message/dto/response/MessageResponseDTO.java
  src/main/java/com/example/template/domain/message/entity/Message.java
  src/main/java/com/example/template/domain/message/entity/MessageImg.java
  src/main/java/com/example/template/domain/message/entity/MessageParticipant.java
  src/main/java/com/example/template/domain/message/entity/ReadStatus.java
  src/main/java/com/example/template/domain/message/entity/enums/ParticipationStatus.java
  src/main/java/com/example/template/domain/message/entity/enums/ReadStatus.java
  src/main/java/com/example/template/domain/message/exception/MessageErrorCode.java
  src/main/java/com/example/template/domain/message/exception/MessageException.java
  src/main/java/com/example/template/domain/message/repository/MessageImgRepository.java
  src/main/java/com/example/template/domain/message/repository/MessageParticipantRepository.java
  src/main/java/com/example/template/domain/message/repository/MessageRepository.java
  src/main/java/com/example/template/domain/message/repository/MessageThreadRepository.java
  src/main/java/com/example/template/domain/message/service/MessageCommandService.java
  src/main/java/com/example/template/domain/message/service/MessageCommandServiceImpl.java
  src/main/java/com/example/template/domain/message/service/MessageQueryService.java
  src/main/java/com/example/template/domain/message/service/MessageQueryServiceImpl.java
  src/main/java/com/example/template/global/config/SwaggerConfig.java
Labels: ♻️ Refactor

#45 ✨ [FEAT] 현재 로그인하여 인증된 Member 어노테이션으로 가져오기 구현 (#44)
  src/main/java/com/example/template/domain/member/controller/MemberController.java
  src/main/java/com/example/template/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/template/domain/member/service/MemberQueryService.java
  src/main/java/com/example/template/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/example/template/global/annotation/AuthenticatedMember.java
  src/main/java/com/example/template/global/annotation/AuthenticatedMemberArgumentResolver.java
  src/main/java/com/example/template/global/config/WebConfig.java
Labels: ✨ Feature

#48 🐛 fix : 충전소 쿼리 수정
  src/main/java/com/example/template/domain/station/entity/Station.java
  src/main/java/com/example/template/domain/station/repository/StationRepository.java
Labels: 🐞 Fix

#51 ♻️ refactor: 차단 기능 리팩토링 (#50)
  src/main/java/com/example/template/domain/block/controller/BlockController.java
  src/main/java/com/example/template/domain/block/dto/response/BlockResponseDTO.java
  src/main/java/com/example/template/domain/block/exception/BlockErrorCode.java
  src/main/java/com/example/template/domain/block/repository/BlockRepository.java
  src/main/java/com/example/template/domain/block/service/BlockCommandService.java
  src/main/java/com/example/template/domain/block/service/BlockCommandServiceImpl.java
  src/main/java/com/example/template/domain/block/service/BlockQueryService.java
  src/main/java/com/example/template/domain/block/service/BlockQueryServiceImpl.java
Labels: ♻️ Refactor

#54 ♻️ refactor: 쪽지 리팩토링 (#49)
  src/main/java/com/example/template/domain/block/controller/BlockController.java
  src/main/java/com/example/template/domain/block/repository/BlockRepository.java
  src/main/java/com/example/template/domain/board/scheduler/UnmappedImageCleanupScheduler.java
  src/main/java/com/example/template/domain/message/controller/MessageController.java
  src/main/java/com/example/template/domain/message/dto/request/MessageRequestDTO.java
  src/main/java/com/example/template/domain/message/dto/response/MessageResponseDTO.java
  src/main/java/com/example/template/domain/message/entity/Message.java
  src/main/java/com/example/template/domain/message/entity/MessageImg.java
  src/main/java/com/example/template/domain/message/exception/MessageErrorCode.java
  src/main/java/com/example/template/domain/message/repository/MessageImgRepository.java
  src/main/java/com/example/template/domain/message/repository/MessageParticipantRepository.java
  src/main/java/com/example/template/domain/message/repository/MessageRepository.java
  src/main/java/com/example/template/domain/message/repository/MessageThreadRepository.java
  src/main/java/com/example/template/domain/message/scheduler/MessageHardDeleteScheduler.java
  src/main/java/com/example/template/domain/message/service/MessageCommandService.java
  src/main/java/com/example/template/domain/message/service/MessageCommandServiceImpl.java
  src/main/java/com/example/template/domain/message/service/MessageQueryService.java
  src/main/java/com/example/template/domain/message/service/MessageQueryServiceImpl.java
  src/main/java/com/example/template/global/common/BaseEntity.java
Labels: ♻️ Refactor

#57 ♻️ refactor: 프로필 API 리팩토링 (#55)
  src/main/java/com/example/template/domain/member/controller/ProfileController.java
  src/main/java/com/example/template/domain/member/dto/ProfileRequestDTO.java
  src/main/java/com/example/template/domain/member/dto/ProfileResponseDTO.java
  src/main/java/com/example/template/domain/member/entity/Member.java
  src/main/java/com/example/template/domain/member/service/MemberCommandService.java
  src/main/java/com/example/template/domain/member/service/MemberCommandServiceImpl.java
Labels: ♻️ Refactor

#53 ✨ [FEAT] 평가(리뷰) API 구현
  src/main/java/com/example/template/domain/review/controller/ReviewController.java
  src/main/java/com/example/template/domain/review/dto/request/ReviewRequestDTO.java
  src/main/java/com/example/template/domain/review/dto/response/ReviewResponseDTO.java
  src/main/java/com/example/template/domain/review/entity/Review.java
  src/main/java/com/example/template/domain/review/entity/ReviewImg.java
  src/main/java/com/example/template/domain/review/enums/SortType.java
  src/main/java/com/example/template/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/example/template/domain/review/exception/ReviewException.java
  src/main/java/com/example/template/domain/review/repository/ReviewImgRepository.java
  src/main/java/com/example/template/domain/review/repository/ReviewKeywordRepository.java
  src/main/java/com/example/template/domain/review/repository/ReviewRecommendRepository.java
  src/main/java/com/example/template/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/template/domain/review/service/KeywordQueryService.java
  src/main/java/com/example/template/domain/review/service/ReviewCommandService.java
  src/main/java/com/example/template/domain/review/service/ReviewQueryService.java
  src/main/java/com/example/template/domain/review/service/impl/KeywordQueryServiceImpl.java
  src/main/java/com/example/template/domain/review/service/impl/ReviewCommandServiceImpl.java
  src/main/java/com/example/template/domain/review/service/impl/ReviewQueryServiceImpl.java
Labels: ✨ Feature

#63 ✨ [FEAT] 카카오 OAuth 구현 (#17)
  build.gradle
  src/main/java/com/example/template/FillEnergyApplication.java
  src/main/java/com/example/template/domain/member/controller/MemberController.java
  src/main/java/com/example/template/domain/member/controller/OAuthController.java
  src/main/java/com/example/template/domain/member/dto/KakaoProfile.java
  src/main/java/com/example/template/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/template/domain/member/dto/RetKakaoOAuth.java
  src/main/java/com/example/template/domain/member/dto/SocialRequestDTO.java
  src/main/java/com/example/template/domain/member/entity/Member.java
  src/main/java/com/example/template/domain/member/entity/ProviderType.java
  src/main/java/com/example/template/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/template/domain/member/repository/MemberRepository.java
  src/main/java/com/example/template/domain/member/service/KakaoService.java
  src/main/java/com/example/template/domain/member/service/KakaoServiceImpl.java
  src/main/java/com/example/template/domain/member/service/MemberService.java
  src/main/java/com/example/template/domain/member/service/MemberServiceImpl.java
  src/main/java/com/example/template/global/config/SecurityConfig.java
  src/main/java/com/example/template/global/config/WebConfig.java
  src/main/resources/templates/social/login.ftl
  src/main/resources/templates/social/redirect.ftl
Labels: ✨ Feature

#65 ✨ feat: 민원 CR API 구현(#62)
  src/main/java/com/example/template/domain/board/scheduler/UnmappedImageCleanupScheduler.java
  src/main/java/com/example/template/domain/complaint/controller/ComplaintController.java
  src/main/java/com/example/template/domain/complaint/dto/request/ComplaintRequestDTO.java
  src/main/java/com/example/template/domain/complaint/dto/response/ComplaintResponseDTO.java
  src/main/java/com/example/template/domain/complaint/entity/Complaint.java
  src/main/java/com/example/template/domain/complaint/entity/ComplaintImg.java
  src/main/java/com/example/template/domain/complaint/exception/ComplaintErrorCode.java
  src/main/java/com/example/template/domain/complaint/exception/ComplaintException.java
  src/main/java/com/example/template/domain/complaint/repository/ComplaintImgRepository.java
  src/main/java/com/example/template/domain/complaint/repository/ComplaintRepository.java
  src/main/java/com/example/template/domain/complaint/service/ComplaintCommandService.java
  src/main/java/com/example/template/domain/complaint/service/ComplaintCommandServiceImpl.java
  src/main/java/com/example/template/domain/complaint/service/ComplaintQueryService.java
  src/main/java/com/example/template/domain/complaint/service/ComplaintQueryServiceImpl.java
Labels: ✨ Feature

#60 ✨ [FEAT] 충전소 즐겨찾기 추가 및 세부 로직 수정
  src/main/java/com/example/template/domain/review/controller/ReviewController.java
  src/main/java/com/example/template/domain/review/dto/request/ReviewRequestDTO.java
  src/main/java/com/example/template/domain/review/dto/response/ReviewResponseDTO.java
  src/main/java/com/example/template/domain/review/entity/Review.java
  src/main/java/com/example/template/domain/review/repository/ReviewImgRepository.java
  src/main/java/com/example/template/domain/review/service/ReviewCommandService.java
  src/main/java/com/example/template/domain/review/service/impl/ReviewCommandServiceImpl.java
  src/main/java/com/example/template/domain/review/validation/annotation/ValidScore.java
  src/main/java/com/example/template/domain/review/validation/validator/ScoreValidator.java
  src/main/java/com/example/template/domain/station/controller/StationController.java
  src/main/java/com/example/template/domain/station/dto/response/StationResponseDTO.java
  src/main/java/com/example/template/domain/station/entity/Station.java
  src/main/java/com/example/template/domain/station/repository/FavoriteRepository.java
  src/main/java/com/example/template/domain/station/repository/StationRepository.java
  src/main/java/com/example/template/domain/station/service/FavoriteCommandService.java
  src/main/java/com/example/template/domain/station/service/FavoriteQueryService.java
  src/main/java/com/example/template/domain/station/service/StationCommandService.java
  src/main/java/com/example/template/domain/station/service/StationQueryService.java
  src/main/java/com/example/template/domain/station/service/impl/FavoriteCommandServiceImpl.java
  src/main/java/com/example/template/domain/station/service/impl/FavoriteQueryServiceImpl.java
  src/main/java/com/example/template/domain/station/service/impl/StationCommandServiceImpl.java
  src/main/java/com/example/template/domain/station/service/impl/StationQueryServiceImpl.java
  src/main/java/com/example/template/global/apiPayload/exception/handler/GlobalExceptionHandler.java
Labels: ✨ Feature, 🐞 Fix

#72 ✨ feat: 마이페이지 커뮤니티 API 구현 (#71)
  src/main/java/com/example/template/domain/board/controller/BoardController.java
  src/main/java/com/example/template/domain/board/controller/CommentController.java
  src/main/java/com/example/template/domain/board/dto/response/BoardResponseDTO.java
  src/main/java/com/example/template/domain/board/dto/response/CommentResponseDTO.java
  src/main/java/com/example/template/domain/board/exception/CommentErrorCode.java
  src/main/java/com/example/template/domain/board/repository/BoardRepository.java
  src/main/java/com/example/template/domain/board/service/commandService/CommentCommandServiceImpl.java
  src/main/java/com/example/template/domain/board/service/queryService/BoardQueryService.java
  src/main/java/com/example/template/domain/board/service/queryService/BoardQueryServiceImpl.java
  src/main/java/com/example/template/domain/board/service/queryService/CommentQueryServiceImpl.java
  src/main/java/com/example/template/domain/member/controller/MemberController.java
Labels: ✨ Feature, ♻️ Refactor

#69 ♻️ refactor: 프로필 리팩토링 (#68)
  src/main/java/com/example/template/domain/member/controller/ProfileController.java
  src/main/java/com/example/template/domain/member/dto/ProfileRequestDTO.java
  src/main/java/com/example/template/domain/member/dto/ProfileResponseDTO.java
  src/main/java/com/example/template/domain/member/entity/GenderType.java
  src/main/java/com/example/template/domain/member/entity/Member.java
  src/main/java/com/example/template/domain/member/entity/MemberType.java
  src/main/java/com/example/template/domain/member/service/MemberCommandService.java
  src/main/java/com/example/template/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/template/domain/member/service/MemberQueryService.java
  src/main/java/com/example/template/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/example/template/domain/review/dto/response/ReviewResponseDTO.java
Labels: ♻️ Refactor

#76 ♻️ refactor: ResponseDTO에 좋아요 여부 필드 추가 (#71)
  src/main/java/com/example/template/domain/board/dto/response/BoardResponseDTO.java
  src/main/java/com/example/template/domain/board/repository/BoardLikeRepository.java
  src/main/java/com/example/template/domain/board/service/commandService/BoardCommandServiceImpl.java
  src/main/java/com/example/template/domain/board/service/queryService/BoardQueryServiceImpl.java
Labels: ♻️ Refactor

#78 🐛 fix: Boolean isLiked 자료형 변경 (#77)
  src/main/java/com/example/template/domain/board/dto/response/BoardResponseDTO.java
  src/main/java/com/example/template/domain/board/service/commandService/BoardCommandServiceImpl.java
  src/main/java/com/example/template/domain/board/service/queryService/BoardQueryServiceImpl.java
Labels: 🐞 Fix

#79 ✨ feat: 내가 쓴 평가 및 충전소 즐겨찾기 수정
  src/main/java/com/example/template/domain/review/controller/ReviewController.java
  src/main/java/com/example/template/domain/review/dto/response/ReviewResponseDTO.java
  src/main/java/com/example/template/domain/review/enums/ContainsQuery.java
  src/main/java/com/example/template/domain/review/enums/SortType.java
  src/main/java/com/example/template/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/template/domain/review/service/ReviewCommandService.java
  src/main/java/com/example/template/domain/review/service/ReviewQueryService.java
  src/main/java/com/example/template/domain/review/service/impl/ReviewCommandServiceImpl.java
  src/main/java/com/example/template/domain/review/service/impl/ReviewQueryServiceImpl.java
  src/main/java/com/example/template/domain/station/controller/StationController.java
  src/main/java/com/example/template/domain/station/dto/response/StationOpenApiResponse.java
  src/main/java/com/example/template/domain/station/dto/response/StationResponseDTO.java
  src/main/java/com/example/template/domain/station/entity/Favorite.java
  src/main/java/com/example/template/domain/station/entity/Station.java
  src/main/java/com/example/template/domain/station/enums/SortType.java
  src/main/java/com/example/template/domain/station/exception/FavoriteErrorCode.java
  src/main/java/com/example/template/domain/station/exception/FavoriteException.java
  src/main/java/com/example/template/domain/station/repository/FavoriteRepository.java
  src/main/java/com/example/template/domain/station/repository/StationRepository.java
  src/main/java/com/example/template/domain/station/service/FavoriteQueryService.java
  src/main/java/com/example/template/domain/station/service/StationQueryService.java
  src/main/java/com/example/template/domain/station/service/impl/FavoriteQueryServiceImpl.java
  src/main/java/com/example/template/domain/station/service/impl/StationQueryServiceImpl.java
Labels: ✨ Feature

#88 🐛 fix: 채팅방 목록 조회 쿼리 및 페이징 처리 로직 수정 (#86)
  src/main/java/com/example/template/domain/block/controller/BlockController.java
  src/main/java/com/example/template/domain/block/service/BlockQueryServiceImpl.java
  src/main/java/com/example/template/domain/message/controller/MessageController.java
  src/main/java/com/example/template/domain/message/entity/Message.java
  src/main/java/com/example/template/domain/message/repository/MessageParticipantRepository.java
  src/main/java/com/example/template/domain/message/service/MessageQueryServiceImpl.java
Labels: ♻️ Refactor, 🐞 Fix

#89 ♻️ refactor: SDK로 받은 토큰으로 인증하기 구현 (#85)
  src/main/java/com/example/template/domain/member/controller/MemberController.java
  src/main/java/com/example/template/domain/member/service/KakaoService.java
  src/main/java/com/example/template/domain/member/service/KakaoServiceImpl.java
Labels: ♻️ Refactor

#90 ♻️ refactor: 첫 쪽지인 경우 threadId로 null 대신 0 사용
  src/main/java/com/example/template/domain/message/service/MessageCommandServiceImpl.java
Labels: ♻️ Refactor

#91 ♻️ refactor: 첫 쪽지인 경우 threadId로 null 대신 0 사용
  src/main/java/com/example/template/domain/message/controller/MessageController.java
Labels: ♻️ Refactor

#87 🐛 fix: 좋아요순 정렬 커뮤니티 게시글 목록 GET API 수정 (#84)
  src/main/java/com/example/template/domain/board/entity/Board.java
  src/main/java/com/example/template/domain/board/repository/BoardRepository.java
  src/main/java/com/example/template/domain/board/service/queryService/BoardQueryServiceImpl.java
Labels: ♻️ Refactor, 🐞 Fix
